//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancingApp.Model.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorSalesRepresentative
    {
        public long SalesRepresentativeId { get; set; }
        public long VendorId { get; set; }
        public string RepresentativeType { get; set; }
    
        public virtual SalesRepresentative SalesRepresentative { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
