//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancingApp.Model.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public Vendor()
        {
            this.VendorSalesRepresentatives = new HashSet<VendorSalesRepresentative>();
            this.Applications = new HashSet<Application>();
        }
    
        public long VendorId { get; set; }
        public string Name { get; set; }
        public long AddressId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<VendorSalesRepresentative> VendorSalesRepresentatives { get; set; }
        public virtual ICollection<Application> Applications { get; set; }
    }
}
