//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancingApp1.Model.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public long ApplicationId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long CustomerId { get; set; }
        public long SalesRepresentativeId { get; set; }
        public long VendorId { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Status { get; set; }
        public Nullable<long> EmployeeId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual SalesRepresentative SalesRepresentative { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
