//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancingApp1.Model.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Applications = new HashSet<Application>();
        }
    
        public long CustomerId { get; set; }
        public string SSN { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public long AddressId { get; set; }
        public Nullable<long> ProfileId { get; set; }
        public string Phone { get; set; }
        public string EmailAddress { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Application> Applications { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
