//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancingApp1.Model.DbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public Profile()
        {
            this.Customers = new HashSet<Customer>();
            this.SalesRepresentatives = new HashSet<SalesRepresentative>();
        }
    
        public long ProfileId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ProfileType { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<SalesRepresentative> SalesRepresentatives { get; set; }
    }
}
